智能硬件:
  - 智能硬件
  - 运动手环
  - 儿童与宠物防丢器
  - 移动医疗监护设备
  - 智能家居
  - 智能眼镜
  - 其他智能硬件

互联网:
  - 网络广告
  - 网络游戏
  - 电子商务
  - 团购
  - B2B
  - C2C
  - O2O
  - 优惠券
  - 票务
  - 比较购物
  - 点评服务
  - 产品搜索
  - 旅游服务
  - 搜索引擎
  - 综合门户
  - 行业网站
  - 网络招聘
  - 网络音乐
  - 社交网络
  - 网上约会
  - 聊天室
  - 微博
  - 论坛
  - 博客
  - 内容聚合
  - 问答
  - 网络服务
  - 即时通讯
  - 电子邮件
  - 云存储
  - 云计算
  - P2P下载
  - 分类信息
  - 电子杂志
  - Wiki
  - RSS 
  - 网络视频
  - 电子支付
  - 网络教育
  - 网络社区
  - 大数据
  - 网上购物
  - 广告营销
  - 网络媒体
  - 旅游预订
  - 互联网金融
  - 网址导航

移动互联网:
  - LBS
  - 移动商务
  - 移动广告
  - 移动支付
  - 移动社交
  - 手机游戏
  - 移动优惠券
  - 移动设备
  - 移动安全
  - 移动搜索
  - 地图服务
  - 二维码
  - iOS
  - Andriod
  - 移动应用
  - 移动终端

IT:
  - 消费电子
  - 电池
  - 嵌入式硬件和软件
  - 显示
  - 存储
  - IC设计
  - IT服务
  - 导航电子地图
  - 数字电视
  - IT新材料
  - 光电科技
